export const USER_LOGIN_WORKING = 'USER_LOGIN_WORKING';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

// Portfolios screen
export const FETCH_PORTFOLIOS_WORKING = 'FETCH_PORTFOLIOS_WORKING';
export const FETCH_PORTFOLIOS_FAILED = 'FETCH_PORTFOLIOS_FAILED';
export const FETCH_PORTFOLIOS_SUCCESSFUL = 'FETCH_PORTFOLIOS_SUCCESSFUL';

// Single Portfolio screen
export const FETCH_SINGLE_PORTFOLIO_WORKING = 'FETCH_SINGLE_PORTFOLIO_WORKING';
export const FETCH_SINGLE_PORTFOLIO_FAILED = 'FETCH_SINGLE_PORTFOLIO_FAILED';
export const FETCH_SINGLE_PORTFOLIO_SUCCESSFUL = 'FETCH_SINGLE_PORTFOLIO_SUCCESSFUL';

// Setup tab
export const FETCH_PORTFOLIO_DETAILS_WORKING = 'FETCH_PORTFOLIO_DETAILS_WORKING';
export const FETCH_PORTFOLIO_DETAILS_FAILED = 'FETCH_PORTFOLIO_DETAILS_FAILED';
export const FETCH_PORTFOLIO_DETAILS_SUCCESSFUL = 'FETCH_PORTFOLIO_DETAILS_SUCCESSFUL';

export const CREATE_PORTFOLIO_CONTACT_WORKING = 'CREATE_PORTFOLIO_CONTACT_WORKING';
export const CREATE_PORTFOLIO_CONTACT_FAILED = 'CREATE_PORTFOLIO_CONTACT_FAILED';
export const CREATE_PORTFOLIO_CONTACT_SUCCESSFUL = 'CREATE_PORTFOLIO_CONTACT_SUCCESSFUL';

export const UPDATE_PORTFOLIO_REQUIREMENTS_WORKING = 'UPDATE_PORTFOLIO_REQUIREMENTS_WORKING';
export const UPDATE_PORTFOLIO_REQUIREMENTS_FAILED = 'UPDATE_PORTFOLIO_REQUIREMENTS_FAILED';
export const UPDATE_PORTFOLIO_REQUIREMENTS_SUCCESSFUL = 'UPDATE_PORTFOLIO_REQUIREMENTS_SUCCESSFUL';

export const UPDATE_COMPANY_STATUS_WORKING = 'UPDATE_COMPANY_STATUS_WORKING';
export const UPDATE_COMPANY_STATUS_FAILED = 'UPDATE_COMPANY_STATUS_FAILED';
export const UPDATE_COMPANY_STATUS_SUCCESSFUL = 'UPDATE_COMPANY_STATUS_SUCCESSFUL';

export const RETRIEVE_ACCOUNT_WORKING = "RETRIEVE_ACCOUNT_WORKING";
export const RETRIEVE_ACCOUNT_FAILED = "RETRIEVE_ACCOUNT_FAILED";
export const RETRIEVE_ACCOUNT_SUCCESSFUL = "RETRIEVE_ACCOUNT_SUCCESSFUL";

export const UPLOAD_LOA_WORKING = "UPLOAD_LOA_WORKING";
export const UPLOAD_LOA_FAILED = "UPLOAD_LOA_FAILED";
export const UPLOAD_LOA_SUCCESSFUL = "UPLOAD_LOA_SUCCESSFUL";

export const UPLOAD_SITELIST_WORKING = "UPLOAD_SITELIST_WORKING";
export const UPLOAD_SITELIST_FAILED = "UPLOAD_SITELIST_FAILED";
export const UPLOAD_SITELIST_SUCCESSFUL = "UPLOAD_SITELIST_SUCCESSFUL";

export const UPLOAD_SUPPLY_METER_DATA_WORKING = "UPLOAD_SUPPLY_METER_DATA_WORKING";
export const UPLOAD_SUPPLY_METER_DATA_FAILED = "UPLOAD_SUPPLY_METER_DATA_FAILED";
export const UPLOAD_SUPPLY_METER_DATA_SUCCESSFUL = "UPLOAD_SUPPLY_METER_DATA_SUCCESSFUL";

export const UPLOAD_HISTORICAL_WORKING = "UPLOAD_HISTORICAL_WORKING";
export const UPLOAD_HISTORICAL_FAILED = "UPLOAD_HISTORICAL_FAILED";
export const UPLOAD_HISTORICAL_SUCCESSFUL = "UPLOAD_HISTORICAL_SUCCESSFUL";

// Meters tab
export const FETCH_METERS_WORKING    = 'FETCH_METERS_WORKING';
export const FETCH_METERS_FAILED     = 'FETCH_METERS_FAILED';
export const FETCH_METERS_SUCCESSFUL = 'FETCH_METERS_SUCCESSFUL';

export const FETCH_MPAN_TOPLINE_WORKING = 'FETCH_MPAN_TOPLINE_WORKING';
export const FETCH_MPAN_TOPLINE_FAILED = 'FETCH_MPAN_TOPLINE_FAILED';
export const FETCH_MPAN_TOPLINE_SUCCESSFUL = 'FETCH_MPAN_TOPLINE_SUCCESSFUL';

export const FETCH_MPAN_HISTORICAL_WORKING = 'FETCH_MPAN_HISTORICAL_WORKING';
export const FETCH_MPAN_HISTORICAL_FAILED = 'FETCH_MPAN_HISTORICAL_FAILED';
export const FETCH_MPAN_HISTORICAL_SUCCESSFUL = 'FETCH_MPAN_HISTORICAL_SUCCESSFUL';

export const UPDATE_PORTFOLIO_METER_WORKING = 'UPDATE_PORTFOLIO_METER_WORKING';
export const UPDATE_PORTFOLIO_METER_FAILED = 'UPDATE_PORTFOLIO_METER_FAILED';
export const UPDATE_PORTFOLIO_METER_SUCCESSFUL = 'UPDATE_PORTFOLIO_METER_SUCCESSFUL';

// Portfolio Summary tab
export const FETCH_PORTFOLIO_HISTORY_WORKING = 'FETCH_PORTFOLIO_HISTORY_WORKING';
export const FETCH_PORTFOLIO_HISTORY_FAILED = 'FETCH_PORTFOLIO_HISTORY_FAILED';
export const FETCH_PORTFOLIO_HISTORY_SUCCESSFUL = 'FETCH_PORTFOLIO_HISTORY_SUCCESSFUL';

export const FETCH_DASHBOARD_SUMMARY_WORKING = 'FETCH_DASHBOARD_SUMMARY_WORKING';
export const FETCH_DASHBOARD_SUMMARY_FAILED = 'FETCH_DASHBOARD_SUMMARY_FAILED';
export const FETCH_DASHBOARD_SUMMARY_SUCCESSFUL = 'FETCH_DASHBOARD_SUMMARY_SUCCESSFUL';

export const FETCH_DASHBOARD_TIMELINE_WORKING = 'FETCH_DASHBOARD_TIMELINE_WORKING';
export const FETCH_DASHBOARD_TIMELINE_FAILED = 'FETCH_DASHBOARD_TIMELINE_FAILED';
export const FETCH_DASHBOARD_TIMELINE_SUCCESSFUL = 'FETCH_DASHBOARD_TIMELINE_SUCCESSFUL';

export const FETCH_DASHBOARD_STATUS_WORKING = 'FETCH_DASHBOARD_STATUS_WORKING';
export const FETCH_DASHBOARD_STATUS_FAILED = 'FETCH_DASHBOARD_STATUS_FAILED';
export const FETCH_DASHBOARD_STATUS_SUCCESSFUL = 'FETCH_DASHBOARD_STATUS_SUCCESSFUL';

// Portfolio creation
export const COMPANY_SEARCH_WORKING = 'COMPANY_SEARCH_WORKING';
export const COMPANY_SEARCH_FAILED = 'COMPANY_SEARCH_FAILED';
export const COMPANY_SEARCH_SUCCESSFUL = 'COMPANY_SEARCH_SUCCESSFUL';
export const COMPANY_SEARCH_CLEAR = 'COMPANY_SEARCH_CLEAR';
export const COMPANY_SEARCH_SELECTED = 'COMPANY_SEARCH_SELECTED';

export const CREATE_ACCOUNT_WORKING = 'CREATE_ACCOUNT_WORKING';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_SUCCESSFUL = 'CREATE_ACCOUNT_SUCCESSFUL';

export const CREATE_PORTFOLIO_WORKING = 'CREATE_PORTFOLIO_WORKING';
export const CREATE_PORTFOLIO_FAILED = 'CREATE_PORTFOLIO_FAILED';
export const CREATE_PORTFOLIO_SUCCESSFUL = 'CREATE_PORTFOLIO_SUCCESSFUL';

export const CLEAR_PORTFOLIO_CREATION = "CLEAR_PORTFOLIO_CREATION";

// Notification actions
export const NOTIFICATION_PORTFOLIO_CREATED = 'NOTIFICATION_PORTFOLIO_CREATED';
export const NOTIFICATION_PORTFOLIO_DELETED = 'NOTIFICATION_PORTFOLIO_DELETED';
export const NOTIFICATION_MPANS_INCLUDED = 'NOTIFICATION_MPANS_INCLUDED';
export const NOTIFICATION_MPANS_EXCLUDED = 'NOTIFICATION_MPANS_EXCLUDED';

export const EDIT_METER = 'EDIT_METER';
export const CANCEL_EDIT_METER = 'CANCEL_EDIT_METER';
