export const FETCH_PORTFOLIOS_WORKING = 'FETCH_PORTFOLIOS_WORKING';
export const FETCH_PORTFOLIOS_FAILED = 'FETCH_PORTFOLIOS_FAILED';
export const FETCH_PORTFOLIOS_SUCCESSFUL = 'FETCH_PORTFOLIOS_SUCCESSFUL';

export const FETCH_PORTFOLIOS_SUMMARY_WORKING = 'FETCH_PORTFOLIOS_SUMMARY_WORKING';
export const FETCH_PORTFOLIOS_SUMMARY_FAILED = 'FETCH_PORTFOLIOS_SUMMARY_FAILED';
export const FETCH_PORTFOLIOS_SUMMARY_SUCCESSFUL = 'FETCH_PORTFOLIO_SUMMARY_SUCCESSFUL';

export const FETCH_PORTFOLIOS_TIMELINE_WORKING = 'FETCH_PORTFOLIOS_TIMELINE_WORKING';
export const FETCH_PORTFOLIOS_TIMELINE_FAILED = 'FETCH_PORTFOLIOS_TIMELINE_FAILED';
export const FETCH_PORTFOLIOS_TIMELINE_SUCCESSFUL = 'FETCH_PORTFOLIOS_TIMELINE_SUCCESSFUL';

export const FETCH_PORTFOLIOS_STATUS_WORKING = 'FETCH_PORTFOLIOS_STATUS_WORKING';
export const FETCH_PORTFOLIOS_STATUS_FAILED = 'FETCH_PORTFOLIOS_STATUS_FAILED';
export const FETCH_PORTFOLIOS_STATUS_SUCCESSFUL = 'FETCH_PORTFOLIOS_STATUS_SUCCESSFUL';