export const USER_LOGIN_WORKING = 'USER_LOGIN_WORKING';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const FETCH_BACKEND_VERSION_WORKING = 'FETCH_BACKEND_VERSION_WORKING';
export const FETCH_BACKEND_VERSION_FAILED = 'FETCH_BACKEND_VERSION_FAILED';
export const FETCH_BACKEND_VERSION_SUCCESSFUL = 'FETCH_BACKEND_VERSION_SUCCESSFUL';

// Portfolios screen
export const FETCH_PORTFOLIOS_WORKING = 'FETCH_PORTFOLIOS_WORKING';
export const FETCH_PORTFOLIOS_FAILED = 'FETCH_PORTFOLIOS_FAILED';
export const FETCH_PORTFOLIOS_SUCCESSFUL = 'FETCH_PORTFOLIOS_SUCCESSFUL';

// Single Portfolio screen
export const FETCH_SINGLE_PORTFOLIO_WORKING = 'FETCH_SINGLE_PORTFOLIO_WORKING';
export const FETCH_SINGLE_PORTFOLIO_FAILED = 'FETCH_SINGLE_PORTFOLIO_FAILED';
export const FETCH_SINGLE_PORTFOLIO_SUCCESSFUL = 'FETCH_SINGLE_PORTFOLIO_SUCCESSFUL';

export const DESELECT_PORTFOLIO = 'DESELECT_PORTFOLIO';

// Setup tab
export const FETCH_PORTFOLIO_DETAILS_WORKING = 'FETCH_PORTFOLIO_DETAILS_WORKING';
export const FETCH_PORTFOLIO_DETAILS_FAILED = 'FETCH_PORTFOLIO_DETAILS_FAILED';
export const FETCH_PORTFOLIO_DETAILS_SUCCESSFUL = 'FETCH_PORTFOLIO_DETAILS_SUCCESSFUL';

export const CREATE_PORTFOLIO_CONTACT_WORKING = 'CREATE_PORTFOLIO_CONTACT_WORKING';
export const CREATE_PORTFOLIO_CONTACT_FAILED = 'CREATE_PORTFOLIO_CONTACT_FAILED';
export const CREATE_PORTFOLIO_CONTACT_SUCCESSFUL = 'CREATE_PORTFOLIO_CONTACT_SUCCESSFUL';

export const UPDATE_PORTFOLIO_REQUIREMENTS_WORKING = 'UPDATE_PORTFOLIO_REQUIREMENTS_WORKING';
export const UPDATE_PORTFOLIO_REQUIREMENTS_FAILED = 'UPDATE_PORTFOLIO_REQUIREMENTS_FAILED';
export const UPDATE_PORTFOLIO_REQUIREMENTS_SUCCESSFUL = 'UPDATE_PORTFOLIO_REQUIREMENTS_SUCCESSFUL';

export const UPDATE_COMPANY_STATUS_WORKING = 'UPDATE_COMPANY_STATUS_WORKING';
export const UPDATE_COMPANY_STATUS_FAILED = 'UPDATE_COMPANY_STATUS_FAILED';
export const UPDATE_COMPANY_STATUS_SUCCESSFUL = 'UPDATE_COMPANY_STATUS_SUCCESSFUL';

export const RETRIEVE_ACCOUNTS_WORKING = "RETRIEVE_ACCOUNTS_WORKING";
export const RETRIEVE_ACCOUNTS_FAILED = "RETRIEVE_ACCOUNTS_FAILED";
export const RETRIEVE_ACCOUNTS_SUCCESSFUL = "RETRIEVE_ACCOUNTS_SUCCESSFUL";

export const RETRIEVE_ACCOUNT_DETAIL_WORKING = "RETRIEVE_ACCOUNT_DETAIL_WORKING";
export const RETRIEVE_ACCOUNT_DETAIL_FAILED = "RETRIEVE_ACCOUNT_DETAIL_FAILED";
export const RETRIEVE_ACCOUNT_DETAIL_SUCCESSFUL = "RETRIEVE_ACCOUNT_DETAIL_SUCCESSFUL";

export const RETRIEVE_ACCOUNT_WORKING = "RETRIEVE_ACCOUNT_WORKING";
export const RETRIEVE_ACCOUNT_FAILED = "RETRIEVE_ACCOUNT_FAILED";
export const RETRIEVE_ACCOUNT_SUCCESSFUL = "RETRIEVE_ACCOUNT_SUCCESSFUL";

export const UPLOAD_LOA_WORKING = "UPLOAD_LOA_WORKING";
export const UPLOAD_LOA_FAILED = "UPLOAD_LOA_FAILED";
export const UPLOAD_LOA_SUCCESSFUL = "UPLOAD_LOA_SUCCESSFUL";

export const UPLOAD_SITELIST_WORKING = "UPLOAD_SITELIST_WORKING";
export const UPLOAD_SITELIST_FAILED = "UPLOAD_SITELIST_FAILED";
export const UPLOAD_SITELIST_SUCCESSFUL = "UPLOAD_SITELIST_SUCCESSFUL";

export const UPLOAD_SUPPLY_METER_DATA_WORKING = "UPLOAD_SUPPLY_METER_DATA_WORKING";
export const UPLOAD_SUPPLY_METER_DATA_FAILED = "UPLOAD_SUPPLY_METER_DATA_FAILED";
export const UPLOAD_SUPPLY_METER_DATA_SUCCESSFUL = "UPLOAD_SUPPLY_METER_DATA_SUCCESSFUL";

export const UPLOAD_HISTORICAL_WORKING = "UPLOAD_HISTORICAL_WORKING";
export const UPLOAD_HISTORICAL_FAILED = "UPLOAD_HISTORICAL_FAILED";
export const UPLOAD_HISTORICAL_SUCCESSFUL = "UPLOAD_HISTORICAL_SUCCESSFUL";

// Meters tab
export const FETCH_METERS_WORKING    = 'FETCH_METERS_WORKING';
export const FETCH_METERS_FAILED     = 'FETCH_METERS_FAILED';
export const FETCH_METERS_SUCCESSFUL = 'FETCH_METERS_SUCCESSFUL';

export const FETCH_METER_CONSUMPTION_WORKING    = 'FETCH_METER_CONSUMPTION_WORKING';
export const FETCH_METER_CONSUMPTION_FAILED     = 'FETCH_METER_CONSUMPTION_FAILED';
export const FETCH_METER_CONSUMPTION_SUCCESSFUL = 'FETCH_METER_CONSUMPTION_SUCCESSFUL';

export const EXPORT_METER_CONSUMPTION_WORKING    = 'EXPORT_METER_CONSUMPTION_WORKING';
export const EXPORT_METER_CONSUMPTION_FAILED     = 'EXPORT_METER_CONSUMPTION_FAILED';
export const EXPORT_METER_CONSUMPTION_SUCCESSFUL = 'EXPORT_METER_CONSUMPTION_SUCCESSFUL';

export const UPDATE_PORTFOLIO_METER_WORKING = 'UPDATE_PORTFOLIO_METER_WORKING';
export const UPDATE_PORTFOLIO_METER_FAILED = 'UPDATE_PORTFOLIO_METER_FAILED';
export const UPDATE_PORTFOLIO_METER_SUCCESSFUL = 'UPDATE_PORTFOLIO_METER_SUCCESSFUL';

export const EXCLUDE_METERS_WORKING = 'EXCLUDE_METERS_WORKING';
export const EXCLUDE_METERS_FAILED = 'EXCLUDE_METERS_FAILED';
export const EXCLUDE_METERS_SUCCESSFUL = 'EXCLUDE_METERS_SUCCESSFUL';

export const INCLUDE_METERS_WORKING = 'INCLUDE_METERS_WORKING';
export const INCLUDE_METERS_FAILED = 'INCLUDE_METERS_FAILED';
export const INCLUDE_METERS_SUCCESSFUL = 'INCLUDE_METERS_SUCCESSFUL';

// Uploads
export const FETCH_PORTFOLIO_UPLOADS_WORKING = 'FETCH_PORTFOLIO_UPLOADS_WORKING';
export const FETCH_PORTFOLIO_UPLOADS_FAILED = 'FETCH_PORTFOLIO_UPLOADS_FAILED';
export const FETCH_PORTFOLIO_UPLOADS_SUCCESSFUL = 'FETCH_PORTFOLIO_UPLOADS_SUCCESSFUL';

export const FETCH_UPLOAD_REPORT_WORKING = 'FETCH_UPLOAD_REPORT_WORKING';
export const FETCH_UPLOAD_REPORT_FAILED = 'FETCH_UPLOAD_REPORT_FAILED';
export const FETCH_UPLOAD_REPORT_SUCCESSFUL = 'FETCH_UPLOAD_REPORT_SUCCESSFUL';

// Portfolio Summary tab
export const FETCH_PORTFOLIO_HISTORY_WORKING = 'FETCH_PORTFOLIO_HISTORY_WORKING';
export const FETCH_PORTFOLIO_HISTORY_FAILED = 'FETCH_PORTFOLIO_HISTORY_FAILED';
export const FETCH_PORTFOLIO_HISTORY_SUCCESSFUL = 'FETCH_PORTFOLIO_HISTORY_SUCCESSFUL';

export const FETCH_DASHBOARD_SUMMARY_WORKING = 'FETCH_DASHBOARD_SUMMARY_WORKING';
export const FETCH_DASHBOARD_SUMMARY_FAILED = 'FETCH_DASHBOARD_SUMMARY_FAILED';
export const FETCH_DASHBOARD_SUMMARY_SUCCESSFUL = 'FETCH_DASHBOARD_SUMMARY_SUCCESSFUL';

export const FETCH_DASHBOARD_TIMELINE_WORKING = 'FETCH_DASHBOARD_TIMELINE_WORKING';
export const FETCH_DASHBOARD_TIMELINE_FAILED = 'FETCH_DASHBOARD_TIMELINE_FAILED';
export const FETCH_DASHBOARD_TIMELINE_SUCCESSFUL = 'FETCH_DASHBOARD_TIMELINE_SUCCESSFUL';

export const FETCH_DASHBOARD_STATUS_WORKING = 'FETCH_DASHBOARD_STATUS_WORKING';
export const FETCH_DASHBOARD_STATUS_FAILED = 'FETCH_DASHBOARD_STATUS_FAILED';
export const FETCH_DASHBOARD_STATUS_SUCCESSFUL = 'FETCH_DASHBOARD_STATUS_SUCCESSFUL';

// Portfolio creation
export const COMPANY_SEARCH_WORKING = 'COMPANY_SEARCH_WORKING';
export const COMPANY_SEARCH_FAILED = 'COMPANY_SEARCH_FAILED';
export const COMPANY_SEARCH_SUCCESSFUL = 'COMPANY_SEARCH_SUCCESSFUL';
export const COMPANY_SEARCH_CLEAR = 'COMPANY_SEARCH_CLEAR';
export const COMPANY_SEARCH_SELECTED = 'COMPANY_SEARCH_SELECTED';

export const CREATE_PORTFOLIO_WORKING = 'CREATE_PORTFOLIO_WORKING';
export const CREATE_PORTFOLIO_FAILED = 'CREATE_PORTFOLIO_FAILED';
export const CREATE_PORTFOLIO_SUCCESSFUL = 'CREATE_PORTFOLIO_SUCCESSFUL';

export const CLEAR_PORTFOLIO_CREATION = "CLEAR_PORTFOLIO_CREATION";

// Accounts

export const CREATE_ACCOUNT_WORKING = 'CREATE_ACCOUNT_WORKING';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_SUCCESSFUL = 'CREATE_ACCOUNT_SUCCESSFUL';

export const UPDATE_ACCOUNT_WORKING = 'UPDATE_ACCOUNT_WORKING';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';
export const UPDATE_ACCOUNT_SUCCESSFUL = 'UPDATE_ACCOUNT_SUCCESSFUL';

export const CREATE_ACCOUNT_CONTACT_WORKING = 'CREATE_ACCOUNT_CONTACT_WORKING';
export const CREATE_ACCOUNT_CONTACT_FAILED = 'CREATE_ACCOUNT_CONTACT_FAILED';
export const CREATE_ACCOUNT_CONTACT_SUCCESSFUL = 'CREATE_ACCOUNT_CONTACT_SUCCESSFUL';

export const UPDATE_ACCOUNT_CONTACT_WORKING = 'UPDATE_ACCOUNT_CONTACT_WORKING';
export const UPDATE_ACCOUNT_CONTACT_FAILED = 'UPDATE_ACCOUNT_CONTACT_FAILED';
export const UPDATE_ACCOUNT_CONTACT_SUCCESSFUL = 'UPDATE_ACCOUNT_CONTACT_SUCCESSFUL';

export const DELETE_ACCOUNT_CONTACT_WORKING = 'DELETE_ACCOUNT_CONTACT_WORKING';
export const DELETE_ACCOUNT_CONTACT_FAILED = 'DELETE_ACCOUNT_CONTACT_FAILED';
export const DELETE_ACCOUNT_CONTACT_SUCCESSFUL = 'DELETE_ACCOUNT_CONTACT_SUCCESSFUL';

export const FETCH_ACCOUNT_DOCUMENTATION_WORKING = 'FETCH_ACCOUNT_DOCUMENTATION_WORKING';
export const FETCH_ACCOUNT_DOCUMENTATION_FAILED = 'FETCH_ACCOUNT_DOCUMENTATION_FAILED';
export const FETCH_ACCOUNT_DOCUMENTATION_SUCCESSFUL = 'FETCH_ACCOUNT_DOCUMENTATION_SUCCESSFUL';

export const UPLOAD_ACCOUNT_DOCUMENTATION_WORKING = 'UPLOAD_ACCOUNT_DOCUMENTATION_WORKING';
export const UPLOAD_ACCOUNT_DOCUMENTATION_FAILED = 'UPLOAD_ACCOUNT_DOCUMENTATION_FAILED';
export const UPLOAD_ACCOUNT_DOCUMENTATION_SUCCESSFUL = 'UPLOAD_ACCOUNT_DOCUMENTATION_SUCCESSFUL';

export const FETCH_ACCOUNT_UPLOADS_WORKING = 'FETCH_ACCOUNT_UPLOADS_WORKING';
export const FETCH_ACCOUNT_UPLOADS_FAILED = 'FETCH_ACCOUNT_UPLOADS_FAILED';
export const FETCH_ACCOUNT_UPLOADS_SUCCESSFUL = 'FETCH_ACCOUNT_UPLOADS_SUCCESSFUL';


// Tenders
export const FETCH_PORTFOLIO_TENDERS_WORKING = 'FETCH_PORTFOLIO_TENDERS_WORKING';
export const FETCH_PORTFOLIO_TENDERS_SUCCESSFUL = 'FETCH_PORTFOLIO_TENDERS_SUCCESSFUL';
export const FETCH_PORTFOLIO_TENDERS_FAILED = 'FETCH_PORTFOLIO_TENDERS_FAILED';

export const FETCH_TENDER_SUPPLIERS_WORKING = 'FETCH_TENDER_SUPPLIERS_WORKING';
export const FETCH_TENDER_SUPPLIERS_SUCCESSFUL = 'FETCH_TENDER_SUPPLIERS_SUCCESSFUL';
export const FETCH_TENDER_SUPPLIERS_FAILED = 'FETCH_TENDER_SUPPLIERS_FAILED';

export const TENDER_ADD_EXISTING_CONTRACT_WORKING = 'TENDER_ADD_EXISTING_CONTRACT_WORKING';
export const TENDER_ADD_EXISTING_CONTRACT_SUCCESSFUL = 'TENDER_ADD_EXISTING_CONTRACT_SUCCESSFUL';
export const TENDER_ADD_EXISTING_CONTRACT_FAILED = 'TENDER_ADD_EXISTING_CONTRACT_FAILED';

export const DELETE_TENDER_WORKING = 'DELETE_TENDER_WORKING';
export const DELETE_TENDER_SUCCESSFUL = 'DELETE_TENDER_SUCCESSFUL';
export const DELETE_TENDER_FAILED = 'DELETE_TENDER_FAILED';

export const CREATE_HH_ELECTRICITY_TENDER_WORKING = 'CREATE_HH_ELECTRICITY_TENDER_WORKING';
export const CREATE_HH_ELECTRICITY_TENDER_SUCCESSFUL = 'CREATE_HH_ELECTRICITY_TENDER_SUCCESSFUL';
export const CREATE_HH_ELECTRICITY_TENDER_FAILED = 'CREATE_HH_ELECTRICITY_TENDER_FAILED';

export const CREATE_NHH_ELECTRICITY_TENDER_WORKING = 'CREATE_NHH_ELECTRICITY_TENDER_WORKING';
export const CREATE_NHH_ELECTRICITY_TENDER_SUCCESSFUL = 'CREATE_NHH_ELECTRICITY_TENDER_SUCCESSFUL';
export const CREATE_NHH_ELECTRICITY_TENDER_FAILED = 'CREATE_NHH_ELECTRICITY_TENDER_FAILED';

export const CREATE_GAS_TENDER_WORKING = 'CREATE_GAS_TENDER_WORKING';
export const CREATE_GAS_TENDER_SUCCESSFUL = 'CREATE_GAS_TENDER_SUCCESSFUL';
export const CREATE_GAS_TENDER_FAILED = 'CREATE_GAS_TENDER_FAILED';

export const UPDATE_TENDER_SUPPLIERS_WORKING = 'UPDATE_TENDER_SUPPLIERS_WORKING';
export const UPDATE_TENDER_SUPPLIERS_SUCCESSFUL = 'UPDATE_TENDER_SUPPLIERS_SUCCESSFUL';
export const UPDATE_TENDER_SUPPLIERS_FAILED = 'UPDATE_TENDER_SUPPLIERS_FAILED';

export const UPLOAD_GAS_BACKING_SHEET_WORKING = "UPLOAD_GAS_BACKING_SHEET_WORKING";
export const UPLOAD_GAS_BACKING_SHEET_FAILED = "UPLOAD_GAS_BACKING_SHEET_FAILED";
export const UPLOAD_GAS_BACKING_SHEET_SUCCESSFUL = "UPLOAD_GAS_BACKING_SHEET_SUCCESSFUL";

export const UPLOAD_ELECTRICITY_BACKING_SHEET_WORKING = "UPLOAD_GAS_BACKING_SHEET_WORKING";
export const UPLOAD_ELECTRICITY_BACKING_SHEET_FAILED = "UPLOAD_GAS_BACKING_SHEET_FAILED";
export const UPLOAD_ELECTRICITY_BACKING_SHEET_SUCCESSFUL = "UPLOAD_GAS_BACKING_SHEET_SUCCESSFUL";

export const UPDATE_TENDER_WORKING = "UPDATE_TENDER_WORKING";
export const UPDATE_TENDER_SUCCESSFUL = 'UPDATE_TENDER_SUCCESSFUL';
export const UPDATE_TENDER_FAILED = 'UPDATE_TENDER_FAILED';

export const FETCH_CONTRACT_BACKINGSHEETS_WORKING = 'FETCH_CONTRACT_BACKINGSHEETS_WORKING';
export const FETCH_CONTRACT_BACKINGSHEETS_SUCCESSFUL = 'FETCH_CONTRACT_BACKINGSHEETS_SUCCESSFUL';
export const FETCH_CONTRACT_BACKINGSHEETS_FAILED = 'FETCH_CONTRACT_BACKINGSHEETS_FAILED';

export const FETCH_QUOTE_BACKINGSHEETS_WORKING = 'FETCH_QUOTE_BACKINGSHEETS_WORKING';
export const FETCH_QUOTE_BACKINGSHEETS_SUCCESSFUL = 'FETCH_QUOTE_BACKINGSHEETS_SUCCESSFUL';
export const FETCH_QUOTE_BACKINGSHEETS_FAILED = 'FETCH_QUOTE_BACKINGSHEETS_FAILED';

export const GENERATE_TENDER_PACK_WORKING = 'GENERATE_TENDER_PACK_WORKING';
export const GENERATE_TENDER_PACK_SUCCESSFUL = 'GENERATE_TENDER_PACK_SUCCESSFUL';
export const GENERATE_TENDER_PACK_FAILED = 'GENERATE_TENDER_PACK_FAILED';

export const ISSUE_TENDER_PACK_WORKING = 'ISSUE_TENDER_PACK_WORKING';
export const ISSUE_TENDER_PACK_SUCCESSFUL = 'ISSUE_TENDER_PACK_SUCCESSFUL';
export const ISSUE_TENDER_PACK_FAILED = 'ISSUE_TENDER_PACK_FAILED';

export const GENERATE_SUMMARY_REPORT_WORKING = 'GENERATE_SUMMARY_REPORT_WORKING';
export const GENERATE_SUMMARY_REPORT_SUCCESSFUL = 'GENERATE_SUMMARY_REPORT_SUCCESSFUL';
export const GENERATE_SUMMARY_REPORT_FAILED = 'GENERATE_SUMMARY_REPORT_FAILED';

export const ISSUE_SUMMARY_REPORT_WORKING = 'ISSUE_SUMMARY_REPORT_WORKING';
export const ISSUE_SUMMARY_REPORT_SUCCESSFUL = 'ISSUE_SUMMARY_REPORT_SUCCESSFUL';
export const ISSUE_SUMMARY_REPORT_FAILED = 'ISSUE_SUMMARY_REPORT_FAILED';

export const FETCH_TENDER_ISSUANCE_EMAIL_WORKING = 'FETCH_TENDER_ISSUANCE_EMAIL_WORKING';
export const FETCH_TENDER_ISSUANCE_EMAIL_SUCCESSFUL = 'FETCH_TENDER_ISSUANCE_EMAIL_SUCCESSFUL';
export const FETCH_TENDER_ISSUANCE_EMAIL_FAILED = 'FETCH_TENDER_ISSUANCE_EMAIL_FAILED';

export const EXPORT_CONTRACT_RATES_WORKING = 'EXPORT_CONTRACT_RATES_WORKING';
export const EXPORT_CONTRACT_RATES_SUCCESSFUL = 'EXPORT_CONTRACT_RATES_SUCCESSFUL';
export const EXPORT_CONTRACT_RATES_FAILED = 'EXPORT_CONTRACT_RATES_FAILED';

export const UPLOAD_GAS_OFFER_WORKING = 'UPLOAD_GAS_OFFER_WORKING';
export const UPLOAD_GAS_OFFER_SUCCESSFUL = 'UPLOAD_GAS_OFFER_SUCCESSFUL';
export const UPLOAD_GAS_OFFER_FAILED = 'UPLOAD_GAS_OFFER_FAILED';

export const UPLOAD_ELECTRICITY_OFFER_WORKING = 'UPLOAD_ELECTRICITY_OFFER_WORKING';
export const UPLOAD_ELECTRICITY_OFFER_SUCCESSFUL = 'UPLOAD_ELECTRICITY_OFFER_SUCCESSFUL';
export const UPLOAD_ELECTRICITY_OFFER_FAILED = 'UPLOAD_ELECTRICITY_OFFER_FAILED';

export const FETCH_TARIFFS_WORKING = 'FETCH_TARIFFS_WORKING';
export const FETCH_TARIFFS_SUCCESSFUL = 'FETCH_TARIFFS_SUCCESSFUL';
export const FETCH_TARIFFS_FAILED = 'FETCH_TARIFFS_FAILED';

export const UPDATE_TENDER_REQUIREMENTS_WORKING = 'UPDATE_TENDER_REQUIREMENTS_WORKING';
export const UPDATE_TENDER_REQUIREMENTS_SUCCESSFUL = 'UPDATE_TENDER_REQUIREMENTS_SUCCESSFUL';
export const UPDATE_TENDER_REQUIREMENTS_FAILED = 'UPDATE_TENDER_REQUIREMENTS_FAILED';

export const DELETE_QUOTE_WORKING = 'DELETE_QUOTE_WORKING';
export const DELETE_QUOTE_SUCCESSFUL = 'DELETE_QUOTE_SUCCESSFUL';
export const DELETE_QUOTE_FAILED = 'DELETE_QUOTE_FAILED';

// Notification actions
export const NOTIFICATION_PORTFOLIO_CREATED = 'NOTIFICATION_PORTFOLIO_CREATED';
export const NOTIFICATION_PORTFOLIO_DELETED = 'NOTIFICATION_PORTFOLIO_DELETED';
export const NOTIFICATION_MPANS_INCLUDED = 'NOTIFICATION_MPANS_INCLUDED';
export const NOTIFICATION_MPANS_EXCLUDED = 'NOTIFICATION_MPANS_EXCLUDED';

export const EDIT_METER = 'EDIT_METER';
export const CANCEL_EDIT_METER = 'CANCEL_EDIT_METER';
